repository: mad4j/photopedia
title: Photopedia
description: A collection of famous photographers
url: ""
baseurl: ""
collections:
  photographers:
    output: true
defaults:
  - scope:
      path: ""
      type: photographers
    values:
      layout: photographer_layout.html
