theme: jekyll-theme-architect
repository: mad4j/photopedia
title: Photopedia
description: A collection of famous photographers
collections:
  photographers:
    output: true
defaults:
  - scope:
      path: ""
      type: photographers
    values:
      layout: photographer_layout.html
plugins:
  - jekyll-github-metadata
